config/routes.rb
Rails.application.routes.draw do
  resources :issues
  resources :settings
  resources :teams
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :recurrent_events
  resources :events
  resources :event_codes
  resources :event_types
  resources :venues
  resources :member_schedules
  resources :members
  get 'home/index'
  root :to => "home#index"
  
#  namespace :admin do
#      resources :users
#      root to: "users#index"
#    end
#  root to: 'visitors#index'
    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "sessions", 
    :passwords => "milia/passwords", 
  }


  resources :users

  get "personal_data_protection", to: "home#personal_data_protection"
  get "display_all_members", to: "members#display_all_members"
  get "display_upcoming_events", to: "events#display_upcoming_events"
  get "display_past_events", to: "events#display_past_events"
  get "display_events_by_member", to: "members#display_events_by_member"
  get "reactivate_member", to: "members#reactivate_member"
  get "member_assignment/:id", to: "events#member_assignment"
  patch "update_member_assignment/:id", to: "events#update_member_assignment"
  get "search_events", to: "events#search_events"
  get "search_members", to: "members#search_members"
  get "change_tenant/:id", to: "members#change_tenant"
  get "display_team_members", to: "teams#display_team_members"
  get "display_members_report", to: "members#display_members_report"
  get "search_members_report", to: "members#search_members_report"
  get "display_my_events", to: "events#display_my_events"
  get "display_all_events", to: "events#display_all_events"
  get "display_member_unavailable_schedule", to: "member_schedules#display_member_unavailable_schedule"
  get "display_users_by_portal", to: "users#display_users_by_portal"
  get "edit_email", to: "users#edit_email"
  patch "update_email", to:"users#update_email"
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  patch "update_report", to: "events#update_report"
  patch "update_attendance", to: "events#update_attendance"
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_tenant!, :only => [ :index ]
  
  

  def index
    #sign_out current_user
    if current_user

      if session[:tenant_id]
        Tenant.set_current_tenant session[:tenant_id]
      else
        Tenant.set_current_tenant current_user.tenants.first
      end
      
      if current_user.member.first.mobile_number.blank? || current_user.member.first.street_name.blank? || current_user.member.first.pdpa.blank?
        flash[:warning] = "Please complete your profile."
        redirect_to edit_user_registration_path(current_user)
      else
        @tenant = Tenant.current_tenant
        params[:tenant_id] = @tenant.id
        
        #Upcoming Event
        @upcoming_events = current_user.member.first.events.where("end_date_time >= ?", Time.current).order(start_date_time: :asc)
        #Check if can take attendance for upcoming
        @event_member = @upcoming_events.empty? ? nil : @upcoming_events.first.event_members.where(member: current_user.member.first.id)
        @upcoming_event = @event_member.blank? ? nil : @upcoming_events.first
        
      end
      
      @issues = Issue.where(status: "Raised") if Tenant.current_tenant.name == "Landlord"
      @tenants = Tenant.where.not(name: "Landlord").order(:name)
    end
  end
  
  def personal_data_protection
    
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="p-2"></div>
<% if current_user && Tenant.current_tenant.name != "Landlord" && current_user.member.first.active_status %>
<%= render "events/attendance" %>
<div class="p-2"></div>
<div class="container">
  <div class="row">
    <div class="col-9 d-none d-lg-block">
      <div class="card text-center border-primary rounded-0">
        <div class="card-header border-primary">
          <ul class="nav nav-pills card-header-pills nav-fill">
            <li class="nav-item">
              <%= link_to "<i class='fa fa-user' aria-hidden='true'></i> Show My Events".html_safe, display_my_events_path, remote: true, class: "btn btn-primary btm-sm bg-white text-primary rounded-0 nav-link" %>
            </li>
            <div class="p-2"></div>
            <li class="nav-item">
              <%= link_to "<i class='fa fa-users' aria-hidden='true'></i> Show All Events".html_safe, display_all_events_path, remote: true, class: "btn btn-primary btm-sm bg-white text-primary rounded-0 nav-link" %>
            </li>
            <div class="p-2"></div>
            <li class="nav-item">
              <div style="float: right;"><button type="button" class="btn btn-primary btm-sm rounded-0" data-toggle="modal" data-target=".bd-example-modal-sm"><i class="fa fa-calendar" aria-hidden="true"></i></button></div>
              <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title">Calendar Legend</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div class="card d-none d-lg-block">
                        <ul class="list-group list-group-flush">
                          <li class="list-group-item bg-success text-white" style="font-size: 0.8em">All Members Assigned</li>
                          <li class="list-group-item bg-warning" style="font-size: 0.8em">Member Partially Assigned</li>
                          <li class="list-group-item bg-danger text-white" style="font-size: 0.8em">Members Not Assigned</li>
                          <li class="list-group-item bg-secondary text-white" style="font-size: 0.8em">Event is Over / Cancelled</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
        <div class="card-body">
          <div id="results">
            <%= render "events/display_home_events", obj: @events, label: @label %>
          </div>  
        </div>
      </div>
    
    </div>
    <div class="col">
      
      <% if @upcoming_events.size > 0 %>
      

      <div class="card rounded-0">
        <div class="card-header text-center bg-primary text-white rounded-0">
          <strong><i class='fa fa-arrow-right' aria-hidden='true'></i> <%= "My Events Agenda".upcase %></strong>
        </div>
        <div class="card-body">
          <div class="list-group list-group-flush text-center">
            
            <% @upcoming_events.each do |event| %>
            
            <a href="<%= event_path(event) %>" class="list-group-item list-group-item-action rounded-0">
              <div class="">
                <h5 class="mb-1"><%= event.name %></h5>
              </div>
              <span class="badge badge-primary badge-pill"><%= distance_of_time_in_words(event.start_date_time, Time.current).capitalize + " to go" %></span><br>
              <small class="text-muted"><%= event.start_date_time.strftime(Event.date_format) %> <br> <%= event.venue.name %></small>
              
            </a>

            <% end %> 

          </div>
        </div>
      </div>
      
      <% else %>
        <div class="alert alert-success" role="alert">
          You have no upcoming events.
        </div>
      <% end %>
      
      <div class="p-2"></div>

    </div>
  </div>
</div>
<% elsif current_user && !current_user.member.first.active_status %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Hello <%= current_user.member.first.first_name%>!</strong> <br>You have been suspended from <%= Tenant.current_tenant.name %> Portal. If you think this is a mistake, please contact your administrator.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% else %>
  <% if !session[:tenant_id].blank? && Tenant.current_tenant.name == "Landlord" %>
    <div class="row">
      <div class="col-6">
        <div class="card border-primary rounded-0">
          <div class="card-body">
            <h5 class="card-title text-primary">List of Portals</h5>
            <p class="card-text">
              <ul class="list-group list-group-flush">
                <% @tenants.each do |tenant| %>
                  <li class="list-group-item"><%= link_to tenant.name, display_users_by_portal_path(tenant), class: "text-dark" %></li>
                <% end %>
              </ul>
            </p>
            
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="card border-danger rounded-0">
          <div class="card-body">
            <h5 class="card-title text-danger">List of Open Issues</h5>
            <p class="card-text"><%= render "issues/display_list_of_open_issues"%></p>
            
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Welcome to Oote Portal</h4>
      <p>Oote Portal is an event personnel management portal to provide highly effective and efficient way of rostering. If you do not have an account, please contact your administrator.</p>
    </div>
  <% end %>
<% end %>