config/routes.rb
Rails.application.routes.draw do
  resources :issues
  resources :settings
  resources :teams
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :recurrent_events
  resources :events
  resources :event_codes
  resources :event_types
  resources :venues
  resources :member_schedules
  resources :members
  get 'home/index'
  root :to => "home#index"
  
#  namespace :admin do
#      resources :users
#      root to: "users#index"
#    end
#  root to: 'visitors#index'
    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "sessions", 
    :passwords => "milia/passwords", 
  }


  resources :users

  get "personal_data_protection", to: "home#personal_data_protection"
  get "display_all_members", to: "members#display_all_members"
  get "display_upcoming_events", to: "events#display_upcoming_events"
  get "display_past_events", to: "events#display_past_events"
  get "display_events_by_member", to: "members#display_events_by_member"
  get "reactivate_member", to: "members#reactivate_member"
  get "member_assignment/:id", to: "events#member_assignment"
  patch "update_member_assignment/:id", to: "events#update_member_assignment"
  get "search_events", to: "events#search_events"
  get "search_members", to: "members#search_members"
  get "change_tenant/:id", to: "members#change_tenant"
  get "display_team_members", to: "teams#display_team_members"
  get "display_members_report", to: "members#display_members_report"
  get "search_members_report", to: "members#search_members_report"
  get "display_my_events", to: "events#display_my_events"
  get "display_all_events", to: "events#display_all_events"
  get "display_member_unavailable_schedule", to: "member_schedules#display_member_unavailable_schedule"
  get "display_users_by_portal", to: "users#display_users_by_portal"
  get "edit_email", to: "users#edit_email"
  patch "update_email", to:"users#update_email"
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  patch "update_report", to: "events#update_report"
  patch "update_attendance", to: "events#update_attendance"
  
  
end

app/models/event_type.rb
class EventType < ApplicationRecord

  acts_as_tenant

  include Hashid::Rails
  
  has_many :event_event_types
  has_many :events, through: :event_event_types
  
  validates_presence_of :name
  validates_uniqueness_of :name, :scope => :tenant_id
  
  has_many :recurrent_event_event_types
  has_many :recurrent_events, through: :recurrent_event_event_types
  
end

app/models/team.rb
class Team < ApplicationRecord
  
  
  acts_as_tenant
  
  has_many :team_members
  has_many :members, through: :team_members


  validates :name, presence: true
  validates_uniqueness_of :name, :scope => :tenant_id


  include Hashid::Rails
  
  def team_descriptor
    name
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authorized_admin_team_leader, only: [:edit, :update, :destroy, :new]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :validates_active_status

  # GET /events
  # GET /events.json
  def index
    #@events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event_logs = EventLogger.where(event_id: @event.id).order(created_at: :desc)
    @event_member = @event.event_members.where(member: current_user.member.first.id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    if @event.status == "Cancelled" || @event.start_date_time < Time.current
      respond_to do |format|
        format.html { redirect_to @event, notice: "#{@event.name} is either cancelled or over." }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.status = @event.check_status(event_params[:member_ids], event_params[:no_of_duty_member])
    @event.recurrent_event_id = 0

    respond_to do |format|
      if @event.save
        Event.send_new_event_creation_email(@event, Tenant.current_tenant.id)
        EventLogger.add_log(@event.id, "Event created by #{current_user.member.first.full_name}")
        format.html { redirect_to action: "member_assignment", id: @event.hashid, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    
    old_event = @event.to_eventstring
    @event.status = @event.check_status(@event.members.as_json, params[:event][:no_of_duty_member])
    
    respond_to do |format|
      if @event.update(event_params)

        #@event.attachment.attach(params[:attachment]) unless params[:attachment].blank?
        
        Event.send_update_event_email(@event, Tenant.current_tenant.id)
        EventLogger.add_log(@event.id, "Event details updated by #{current_user.member.first.full_name} - [ Previous Details -> #{old_event} ] - [ New Details -> #{@event.to_eventstring} ]")
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    #@event.destroy
    respond_to do |format|
      if(@event.update(status: "Cancelled"))
        Event.send_cancel_event_email(@event, Tenant.current_tenant.id)
        EventLogger.add_log(@event.id, "Event cancelled by #{current_user.member.first.full_name}")
        format.html { redirect_to @event, notice: 'Event was successfully cancelled.' }
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def display_upcoming_events
    @upcoming_events = current_user.member.first.events.paginate(page: params[:page], per_page: 10).where("start_date_time >= ? AND status != ?", Time.current, "Cancelled").order(start_date_time: :asc).order('start_date_time')
  end
  
  def display_past_events
    @past_events = current_user.member.first.events.paginate(page: params[:page], per_page: 10).where("start_date_time < ? AND status != ?", Time.current, "Cancelled").order(start_date_time: :desc).order('start_date_time')
  end
  
  def member_assignment
    
  end

  def update_member_assignment
    @event = Event.find(params[:id])
    existing_members = @event.members.as_json
    old_members = @event.to_members_string
    status = @event.status
  
    respond_to do |format|
      @event.status = @event.check_status(event_params[:member_ids], @event.no_of_duty_member)
      if @event.update(event_params)
        if status == "Not assigned"
          Event.send_new_event_email(@event, Tenant.current_tenant.id)
        else
          Event.send_update_event_email(@event, Tenant.current_tenant.id)
          
        end
        
        Event.send_unassigned_member_email(@event, existing_members, Tenant.current_tenant.id)
        EventLogger.add_log(@event.id, "Member assignment updated by #{current_user.member.first.full_name} - [ Previous Members -> #{old_members} ] - [ New Members -> #{@event.to_members_string} ]")
        format.html { redirect_to @event, notice: 'Members were successfully assigned. Emails will be sent to members.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :member_assignment }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end  
  end
  
  def search_events
    
    @events = Event.search_events(params)
    if @events
      respond_to do |format|
        format.js {render partial: 'events/display_events', obj: @events }
      end
    end

  end
  
  def update_report
    @event = Event.find(params[:event][:id])
    old_report = Sanitize.clean(@event.report)
    respond_to do |format|
      if @event.update(event_params)
        EventLogger.add_log(@event.id, "Event report updated by #{current_user.member.first.full_name}  - [ Previous Report -> #{old_report} ] - [ New Report -> #{Sanitize.clean(@event.report)} ]")
        format.html { redirect_to @event, notice: 'Event report was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :show }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_attendance
    @event = Event.find(params[:event][:id])
    @event_member = @event.event_members.where(member: current_user.member.first.id)
    respond_to do |format|
      if @event_member.first.sign_on.blank? ? @event_member.first.update(sign_on: Time.current) : @event_member.first.update(sign_off: Time.current)
        
        EventLogger.add_log(@event.id, "#{current_user.member.first.full_name} signed #{@event_member.first.sign_off.blank? ? 'on' : 'off'} for this event.")
        format.html { redirect_to @event, notice: "Your sign-#{@event_member.first.sign_off.blank? ? 'on' : 'off'} has been registered." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :show }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def display_my_events
    @label = "My".upcase
    @events = current_user.member.first.events
    if @events
      respond_to do |format|
        format.js {render partial: 'events/display_home_events', obj: @events }
      end
    end
  end
  
  def display_all_events
    @label = "All".upcase
    @events = Event.all
    if @events
      respond_to do |format|
        format.js {render partial: 'events/display_home_events', obj: @events }
      end
    end
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start_date_time, :end_date_time, :venue_id, :description, :no_of_duty_member, :name, :status, :recurrent_event_id, :tenant_id, :event_code_id, :report, :attachment, event_type_ids:[], member_ids:[])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attendance.html.erb
<% if !@event_member.blank? && Setting.first.manage_attendance %>
  <% @event = @upcoming_event.blank? ? @event : @upcoming_event  %>
  <% if ((@event_member.first.sign_on.blank?) || (@event_member.first.sign_off.blank?))  && @event.live_event_date_range === Time.current  %>
    <div class="alert alert-warning alert-dismissible fade show col" role="alert">
      <%= form_with model: @event, url: update_attendance_path do |f| %>
      
      <% if @event_member.first.sign_on.blank? %> 
        <strong>Sign ON!</strong> You can sign-in for <%= @event.name %> now. Click <%= f.submit "Sign ON", class: "btn btn-success btn-sm rounded-0" %> now.
      <% else %>
        <strong>Sign OFF!</strong> You can sign-off for <%= @event.name %> now. Click <%= f.submit "Sign OFF", class: "btn btn-danger btn-sm rounded-0", data: { confirm: "You are about to sign OFF, are you sure this is what you want to do?" } %> now.
      <% end %>
      <%= f.hidden_field :id %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/events/_display_events.html.erb
<% if obj %>
  <% if obj.size > 0 %>
  <%= will_paginate obj,  list_classes: %w(pagination justify-content-center), previous_label: "Previous", next_label: "Next"  %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="text-center">Event Name</th>
          <th class="text-center">Date - Time<br>Venue</th>
          <th class="text-center">Duty Members</th>
          <th class="text-center">Event Type</th>
          <th class="text-center">Event Status</th>
          <th class="text-center">Actions</th>
        </tr>
      </thead>
    
      <tbody>
        <% obj.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td class="text-center"><%= event.start_date_time.strftime(date_format) %><br><%= event.venue.name %></td>
            <td><% event.members.each do |member| %>
              <h5 class="text-center"><span class="badge badge-pill badge-primary"><%= member.full_name %></span></h5>
              <% end %>
            </td>
            <td>
              <% event.event_types.each do |type| %>
                <h5 class="text-center"><span class="badge badge-pill badge-info"><%= type.name %></span></h5>
              <% end %>
            </td>
            
            <td><h5 class="text-center"><span class="badge badge-pill badge-<%= event.status_color %>"><%= event.status %></span></h5></td>
            <td class="text-center"><%= link_to "<i class='fa fa-search-plus'></i> Show".html_safe, event, class: "#{submit_button}" %>
            <% if (current_user.member.first.try(:admin?) || current_user.member.first.try(:team_leader?)) && event.status != "Cancelled" && event.start_date_time >= Time.current %>
              <%= link_to "<i class='fa fa-pencil'></i> Edit".html_safe, edit_event_path(event), class: "#{submit_button}" %>
              <div class="p-1"></div>
              <%= link_to "<i class='fa fa-users'></i> Assign Members".html_safe, "/member_assignment/#{event.hashid}", class: "#{submit_button}" %>
              <div class="p-1"></div>
              <%= link_to "<i class='fa fa-user-times'></i> Cancel Event".html_safe, event, method: :delete, data: { confirm: confirm_delete_message }, class: "#{cancel_button}" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate obj,  list_classes: %w(pagination justify-content-center), previous_label: "Previous", next_label: "Next"  %>
  <% else %>
  <br>
  <div class="alert alert-warning" role="alert">
    <h5>No event found.</h5>
  </div>

  <% end %>
<% end %>

app/views/events/_display_events.js.erb
$('#results').html("<%= j ( render 'events/display_events.html', obj: @events) %>");
$('.pagination a').attr('data-remote', 'true');

app/views/events/_display_home_events.html.erb
<% if obj %>
  <% if obj.size > 0%>
    <h4><%= label %> EVENTS</h4>
    <%= month_calendar events: obj do |date, events| %>
      <div class="text-center" style="font-size: 0.7em"><%= date.strftime("%d-%b") %></div><br />
        <% events.each do |event| %>
          <%= link_to event.name, event, class: "btn btn-#{Time.current > event.start_date_time ? "secondary" : event.status_color} btn-sm col", style: "font-size: 0.8em" %><div class="p-1"></div>
        <% end %>
    <% end %>  
  <% end %>
  <% else %>
    <div class="text-left">Select one of the options above to view respective events.</div>
<% end %>

app/views/events/_display_home_events.js.erb
$('#results').html("<%= j ( render 'events/display_home_events.html', obj: @events, label: @label) %>");
$('.pagination a').attr('data-remote', 'true');

app/views/events/display_past_events.html.erb
<h1  class="display-4">My Past Events</h1>
<div class="p-2"></div>
<%= render "display_events", obj: @past_events %>
<div class="p-2"></div>
<%= back_button %>

app/views/events/display_upcoming_events.html.erb
<h1  class="display-4">My Upcoming Events</h1>
<div class="p-2"></div>
<%= render "display_events", obj: @upcoming_events %>
<div class="p-2"></div>
<%= back_button %>

app/views/events/edit.html.erb
<h1 class="display-4">Editing Event</h1>

<div class="p-2"></div>
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<h1  class="display-4">Search Events</h1>

<div class="p-2"></div>

<div id="event-lookup" class="card border-primary mb-3 rounded-0">
  <h6 class="card-header text-white bg-primary rounded-0">Search Parameters</h6>
  
  <%= form_tag search_events_path, remote: true, method: :get, id: "search-events-form" do %>
  <div class="card-body">
    <div class="form-row">
      <div class="form-group col">
        <%= text_field_tag :event, params[:event], placeholder: "Event Title", autofocus: true, class: "form-control" %>
      </div>
      <div class="form-group col">
        <div class="input-group date" id="datetimepicker7" data-target-input="nearest">
            <%= text_field_tag :from_start_date, nil,  class: "form-control datetimepicker-input", readonly: true, data: {target: "#datetimepicker7"}, placeholder: "From - Start Date" %>
            <div class="input-group-append" data-target="#datetimepicker7" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    
      <div class="form-group col">
        <div class="input-group date col" id="datetimepicker8" data-target-input="nearest">
          <%= text_field_tag :to_start_date, nil, class: "form-control datetimepicker-input", readonly: true, data: {target: "#datetimepicker8"}, placeholder: "To - Start Date" %>
            <div class="input-group-append" data-target="#datetimepicker8" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
      </div>
      <div class="form-row">
      <div class="form-group col">
        <%= select_tag :venue, options_from_collection_for_select(Venue.all, :id, :venue_descriptor),  {:class =>"selectpicker form-control", :title => "Venue", :data => {:'live-search' => true}} %>
      </div>
      <% if Setting.first.manage_event_code? %>
        <div class="form-group col">
          <%= select_tag :event_code, options_from_collection_for_select(EventCode.all, :id, :code), {:class =>"selectpicker form-control", :title => "Event Code", :data => {:'live-search' => true}} %>
        </div>
      <% end %>
      <div class="form-group col">
        <%= select_tag :status, options_for_select(["Not assigned","Partially assigned","Assigned", "Cancelled"]),  {:class =>"selectpicker form-control", :title => "Event Status", :data => {:'live-search' => true}} %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col text-center">
        <%= button_tag type: "submit", class: "#{submit_button}" do %> <i class='fa fa-search'></i> Search Event <% end %>
        <%= link_to "<i class='fa fa-ban'></i> Clear".html_safe, events_path, class: "#{cancel_button}" %> 
        <%= link_to "<i class='fa fa-calendar'></i> New Event".html_safe, new_event_path, class: "#{submit_button}" %>
      </div>
    </div>
    </div>
  <% end %>
</div>

<div class="p-2"></div>

<div id="results">
  <%= render "display_events", obj: @events %>
</div>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker7').datetimepicker({
            format: "DD-MMM-YYYY - h:mm A",
            stepping: 30,
            ignoreReadonly: true
        });
        $('#datetimepicker8').datetimepicker({
            useCurrent: false,
            format: "DD-MMM-YYYY - h:mm A",
            stepping: 30,
            ignoreReadonly: true
        });
        $("#datetimepicker7").on("change.datetimepicker", function (e) {
            $('#datetimepicker8').datetimepicker('minDate', e.date);
            $('#datetimepicker8').datetimepicker('date', e.date.add(2, 'hours'));
        });
        $("#datetimepicker8").on("change.datetimepicker", function (e) {
            //$('#datetimepicker7').datetimepicker('maxDate', e.date);
        });
        
        $(".selectpicker").selectpicker({
        }).selectpicker("render");
        
        $('.pagination a').attr('data-remote', 'true')
    });
</script>

app/views/events/member_assignment.html.erb
<% if params[:notice].present? %>
<div class="alert alert-success fade show">
  <button class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= params[:notice]  %>
</div>
<% end %>
<% @event = Event.find(params[:id]) %>

<h1 class="display-4">Member Assignment</h1>
<h6>For <%= @event.name %> on <%= @event.start_date_time.strftime(date_format) %> at <%= @event.venue.name %> </h6>

<div class="p-2"></div>
<%= form_for(@event, local: true, :url => {:action => "update_member_assignment"}) do |form| %>

  <div class="p-2"></div>
    <div class="card border-primary mb-3 rounded-0">
      <div class="card-header bg-primary text-white rounded-0">Assign Members for <%= @event.name %></div>
        <div class="card-body text-dark">  
        
        <div class="form-row">
  
        
          <div class="form-group col" id="members-assignment">
            <%= form.label "List of Available Members" %>
            <%= form.collection_select :member_ids, Member.available_members(@event.start_date_time, @event.end_date_time, @event.id, current_user), :id, :member_descriptor, {},  {:class =>"selectpicker form-control show-tick", :multiple => true, :data => {:'live-search' => true }} %>
            <small class="form-text text-muted">Names are sorted by home shortest to farthest distance from <%= @event.venue.name %></small>
          </div>
        </div>
        </div>
  </div>
  <div class="p-2"></div>
  <div class="form-group">
    <%= button_tag type: "submit", class: "#{submit_button}" do %> <i class='fa fa-users'></i> Assign Member for <%= @event.name %> <% end %>
    <%= link_to "<i class='fa fa-mail-forward'></i> Skip Member Assignment".html_safe, @event, class: "#{submit_button}" %>
  </div>
  
<% end %>

<script type="text/javascript">
    $(function () {

        $(".selectpicker").selectpicker({
        }).selectpicker("render");
    });
</script>

app/views/events/new.html.erb
<h1 class="display-4">New Event</h1>

<div class="p-2"></div>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= render "events/attendance" %>
<div class="card  border-0 mb-3 rounded-0">
  <div class="container">
    <h1 class="text-uppercase text-center text-primary p-2 font-weight-boold"><%= @event.name%></h1>
    <p class="lead text-center"><%= @event.description %></p>
    <hr class="my-4">
    <table class="table table-striped">
      <thead>
      </thead>
      <tbody>
        <tr>
          <th scope="row" class="text-right">Date and Start Time : </th>
          <td><%= @event.start_date_time.strftime(date_format) %></td>
        </tr>
        <tr>
          <th scope="row" class="text-right">Date and End Time : </th>
          <td><%= @event.end_date_time.strftime(date_format) %></td>
        </tr>
        <tr>
          <th scope="row" class="text-right">Venue : </th>
          <td><%= @event.venue.name %> <%= link_to "<i class='fa fa-map-marker'></i>".html_safe, @event.venue.url, target: :blank, class: "" %></td>
        </tr>
        <tr>
          <th scope="row" class="text-right">Duty Members : <br>
            <% if Setting.first.manage_attendance %>
              <small>Legend: <span class="badge badge-pill badge-secondary">Not Started</span> <span class="badge badge-pill badge-warning">Sign-on</span> <span class="badge badge-pill badge-success">Sign-off</span> <span class="badge badge-pill badge-danger">Absent</span></small>
            <% end %>
          </th>
          <td><h5><% @event.members.each do |member| %>
            <span class="badge badge-pill badge-<%= !member.event_members.where(event_id: @event.id).first.sign_off.blank? ? 'success' : (!member.event_members.where(event_id: @event.id).first.sign_on.blank? && member.event_members.where(event_id: @event.id).first.sign_off.blank? ) ? 'warning' : @event.end_date_time < Time.current ? 'danger' : 'secondary' %>"><%= member.full_name %> <%= " - " + member.mobile_number if Setting.first.display_phone%></span>
            <% end %></h5>
          </td>
        </tr>
        <tr>
          <th scope="row" class="text-right">Event Type : </th>
          <td><h5>
            <% @event.event_types.each do |type| %>
              <span class="badge badge-pill badge-info" data-toggle="tooltip" data-placement="bottom" title="<%= type.description %>"><%= type.name %></span>
            <% end %>
            </h5>
          </td>
        </tr>
        <% if Setting.first.manage_event_code %>
        <tr>
          <th scope="row" class="text-right">Event Code : </th>
          <td><%= @event.event_code.present? ? @event.event_code.code : "N/A" %>-<%= @event.start_date_time.strftime(event_code_format) %>
          </td>
        </tr>
        <% end %>
          <th scope="row" class="text-right">Status : </th>
          <td><%= @event.status %></td>
        </tr> 
        <% if Setting.first.manage_event_report %>
        <tr>
          <th scope="row" class="text-right">Members' Report : </th>
          <td>
              <% if @event.report.blank? && @event.live_event_date_range === Time.current %>
                <button type='button' class="<%= submit_button %>" data-toggle='modal' data-target='#event_report'>Add Report</button>
              <% else %>
                <%= @event.report.html_safe if !@event.report.blank? %>
                <% if @event.live_event_date_range === Time.current %> 
                  <div class="p-2"></div>
                  <button type='button' class="<%= submit_button %>" data-toggle='modal' data-target='#event_report'>Edit Report</button> 
                <% else %>
                  <small>Add or edit of report is not allowed now. </small>
                <% end %>
              <% end %>
          </td>
          <%= form_with(model: @event, local: true, url: update_report_path) do |f| %>
            <div class="modal fade" id="event_report" tabindex="-1" role="dialog" aria-labelledby="event_report" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><%= @event.report.blank? ? "Add" : "Update" %> an Event Report</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= form_with(model: @event, local: true, url: update_report_path) do |f| %>
                      <%= f.text_area :report, class: "tinymce" %>
                        <%= tinymce %>
                      <%= f.hidden_field :id %>
                      <div class="p-2"></div>
                      <%= f.submit "#{ @event.report.blank? ? "Add Report" : "Update Report"}", class: "#{submit_button}"%>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% if current_user.member.first.try(:admin?) %>
    <button class="<%= submit_button %>" type="button" data-toggle="collapse" data-target="#eventhistory" aria-expanded="false" aria-controls="collapseExample">
      <i class="fa fa-history"></i> Show Event History
    </button>
    <div class="p-2"></div>
    <div class="collapse col" id="eventhistory">
      <div class="card border-dark mb-3 rounded-0">
        <div class="card-header rounded-0"><strong>Event Update History</strong></div>
          <ul class="list-group list-group-flush">
            <% @event_logs.each do |event_log| %>
              <li class="list-group-item" style="font-size: 0.7em"><%= event_log.event_log %></li>
            <% end %>
          </ul>
      </div>
    </div>
    <% end %>
    <% if @event.status != "Cancelled" && current_user.member.first.try(:admin?) && @event.start_date_time >= Time.current %>
      <%= link_to "<i class='fa fa-pencil'></i> Edit".html_safe, edit_event_path(@event), class: "#{submit_button}" %> 
      <%= link_to "<i class='fa fa-users'></i> Assign Members".html_safe, "/member_assignment/#{@event.hashid}", class: "#{submit_button}" %>
      <%= link_to "<i class='fa fa-ban'></i> Cancel Event".html_safe, event_path(@event), method: :delete, data: { confirm: confirm_delete_message }, class: "#{cancel_button}" %>
    <% end %> 
    <%= back_button %>
  </div>
</div>