config/routes.rb
Rails.application.routes.draw do
  resources :issues
  resources :settings
  resources :teams
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :recurrent_events
  resources :events
  resources :event_codes
  resources :event_types
  resources :venues
  resources :member_schedules
  resources :members
  get 'home/index'
  root :to => "home#index"
  
#  namespace :admin do
#      resources :users
#      root to: "users#index"
#    end
#  root to: 'visitors#index'
    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "sessions", 
    :passwords => "milia/passwords", 
  }


  resources :users

  get "personal_data_protection", to: "home#personal_data_protection"
  get "display_all_members", to: "members#display_all_members"
  get "display_upcoming_events", to: "events#display_upcoming_events"
  get "display_past_events", to: "events#display_past_events"
  get "display_events_by_member", to: "members#display_events_by_member"
  get "reactivate_member", to: "members#reactivate_member"
  get "member_assignment/:id", to: "events#member_assignment"
  patch "update_member_assignment/:id", to: "events#update_member_assignment"
  get "search_events", to: "events#search_events"
  get "search_members", to: "members#search_members"
  get "change_tenant/:id", to: "members#change_tenant"
  get "display_team_members", to: "teams#display_team_members"
  get "display_members_report", to: "members#display_members_report"
  get "search_members_report", to: "members#search_members_report"
  get "display_my_events", to: "events#display_my_events"
  get "display_all_events", to: "events#display_all_events"
  get "display_member_unavailable_schedule", to: "member_schedules#display_member_unavailable_schedule"
  get "display_users_by_portal", to: "users#display_users_by_portal"
  get "edit_email", to: "users#edit_email"
  patch "update_email", to:"users#update_email"
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  patch "update_report", to: "events#update_report"
  patch "update_attendance", to: "events#update_attendance"
  
  
end

app/controllers/event_types_controller.rb
class EventTypesController < ApplicationController
  
  before_action :authorized_admin
  before_action :set_event_type, only: [:show, :edit, :update, :destroy]
  before_action :validates_active_status

  # GET /event_types
  # GET /event_types.json
  def index
    @event_types = EventType.all.order(:name)
  end

  # GET /event_types/1
  # GET /event_types/1.json
  def show
  end

  # GET /event_types/new
  def new
    @event_type = EventType.new
  end

  # GET /event_types/1/edit
  def edit
  end

  # POST /event_types
  # POST /event_types.json
  def create
    @event_type = EventType.new(event_type_params)

    respond_to do |format|
      if @event_type.save
        format.html { redirect_to event_types_path, notice: 'Event type was successfully created.' }
        format.json { render :show, status: :created, location: @event_type }
      else
        format.html { render :new }
        format.json { render json: @event_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_types/1
  # PATCH/PUT /event_types/1.json
  def update
    respond_to do |format|
      if @event_type.update(event_type_params)
        format.html { redirect_to event_types_url, notice: 'Event type was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_type }
      else
        format.html { render :edit }
        format.json { render json: @event_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_types/1
  # DELETE /event_types/1.json
  def destroy
    #@event_type.destroy
    respond_to do |format|
      format.html { redirect_to event_types_url, notice: 'Event type was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_type
      @event_type = EventType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_type_params
      params.require(:event_type).permit(:name, :description)
    end
end

app/helpers/event_types_helper.rb
module EventTypesHelper
end

app/views/event_types/_form.html.erb
<%= render "layouts/errors", object: event_type %>

<div class="card border-primary mb-3 rounded-0">
  <h6 class="card-header bg-primary text-white rounded-0">Event Type</h6>
  <div class="card-body">
    <%= form_with(model: event_type, local: true) do |form| %>

  
    <div class="form-group">
        <%= form.label "Event Type" %>
        <%= form.text_field :name, class: "form-control", required: true  %>
    </div>
  
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control", required: true  %>
    </div>
  
    <div class="actions">
      <%= form.submit class: "#{submit_button}" %> <%= back_button %>
    </div>
  <% end %>
  </div>
</div>

app/views/event_types/edit.html.erb
<h1 class="display-4">Editing Event Type</h1>
<div class="p-2"></div>
<%= render 'form', event_type: @event_type %>

app/views/event_types/index.html.erb
<h1 class="display-4">Event Type List</h1>
<div class="p-2"></div>
<%= link_to "<i class='fa fa-calendar-check-o'></i> New Event Type".html_safe, new_event_type_path, class: "#{submit_button}" %>
<div class="p-2"></div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Event Type</th>
      <th>Description</th>
      <th >Action</th>
    </tr>
  </thead>

  <tbody>
    <% @event_types.each do |event_type| %>
      <tr>
        <td><%= event_type.name %></td>
        <td><%= event_type.description %>
        <td><%= link_to "<i class='fa fa-pencil'></i> Edit".html_safe, edit_event_type_path(event_type), class: "#{submit_button}" %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="p-2"></div>
<%= link_to "<i class='fa fa-calendar-check-o'></i> New Event Type".html_safe, new_event_type_path, class: "#{submit_button}" %>

app/views/event_types/new.html.erb
<h1 class="display-4">New Event Type</h1>
<div class="p-2"></div>
<%= render 'form', event_type: @event_type %>