config/routes.rb
Rails.application.routes.draw do
  resources :issues
  resources :settings
  resources :teams
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :recurrent_events
  resources :events
  resources :event_codes
  resources :event_types
  resources :venues
  resources :member_schedules
  resources :members
  get 'home/index'
  root :to => "home#index"
  
#  namespace :admin do
#      resources :users
#      root to: "users#index"
#    end
#  root to: 'visitors#index'
    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "sessions", 
    :passwords => "milia/passwords", 
  }


  resources :users

  get "personal_data_protection", to: "home#personal_data_protection"
  get "display_all_members", to: "members#display_all_members"
  get "display_upcoming_events", to: "events#display_upcoming_events"
  get "display_past_events", to: "events#display_past_events"
  get "display_events_by_member", to: "members#display_events_by_member"
  get "reactivate_member", to: "members#reactivate_member"
  get "member_assignment/:id", to: "events#member_assignment"
  patch "update_member_assignment/:id", to: "events#update_member_assignment"
  get "search_events", to: "events#search_events"
  get "search_members", to: "members#search_members"
  get "change_tenant/:id", to: "members#change_tenant"
  get "display_team_members", to: "teams#display_team_members"
  get "display_members_report", to: "members#display_members_report"
  get "search_members_report", to: "members#search_members_report"
  get "display_my_events", to: "events#display_my_events"
  get "display_all_events", to: "events#display_all_events"
  get "display_member_unavailable_schedule", to: "member_schedules#display_member_unavailable_schedule"
  get "display_users_by_portal", to: "users#display_users_by_portal"
  get "edit_email", to: "users#edit_email"
  patch "update_email", to:"users#update_email"
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  patch "update_report", to: "events#update_report"
  patch "update_attendance", to: "events#update_attendance"
  
  
end

app/models/member.rb
class Member < ApplicationRecord
   
  belongs_to :user
  has_many :member_schedules
  
  has_many :event_members
  has_many :events, through: :event_members
  
  has_many :team_members
  has_many :teams, through: :team_members

  geocoded_by :street_name, latitude: :latitude, longitude: :longitude
  after_validation :geocode

  include Hashid::Rails
  include ApplicationHelper
  
  
  validates :mobile_number, presence: true, length: {minimum: 8, maximum: 8}
  validates :street_name, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :region, presence: true
  validates :role, presence: true
  validates :team_ids, presence: true, unless: :skip_team_validation
  validates_acceptance_of :pdpa, accept: true
  
  attribute :active_status, default: true
  
  attr_accessor :skip_team_validation

  acts_as_tenant
  #acts_as_universal 
  
  DEFAULT_ADMIN = {
    first_name: "Admin",
    last_name:  "Please edit me",
    role: :admin,
    active_status: true
  }
  
  enum role: [:user, :team_leader, :admin]

  def self.create_new_member(user, params)
    # add any other initialization for a new member
    # return user.create_member( params )
    return Member.create_member(user, params)
  end

  def self.create_org_admin(user)
    new_member = create_new_member(user, DEFAULT_ADMIN)
    unless new_member.errors.empty?
      raise ArgumentError, new_member.errors.full_messages.uniq.join(", ")
    end

    Team.create(name: "General", description: "General")
    Setting.create(send_sms: false) if Setting.first.blank?

    return new_member
      
  end
  
  def full_name
    first_name + " " + last_name
  end


  def self.available_members(start_date, end_date, event_id, current_user)
    @members = Array.new
    current_date_range = start_date..end_date
    
    venue_coordinates = Event.find(event_id).convert_to_coordinates
    members_by_distance = Member.near(venue_coordinates, 100, unit: :km, order: 'distance')
    members_by_distance.each do |member|
        @members << member if ((!member.events.any? { |event| event.date_range.overlaps?(current_date_range) && 
        event.status != "Cancelled" } && 
        !member.member_schedules.any? { |unavailable| unavailable.date_range.overlaps?(current_date_range) } &&
        member.active_status? &&
        (member.teams.any? { |team| current_user.member.first.teams.exists?(team.id) } || current_user.member.first.try(:admin?))) || 
        member.events.any? { |event| event.id == event_id })
    end
    
    
    return @members

  end

  def convert_to_coordinates
    
    coordinates << latitude
    coordinates << longtitude
    
  end
  
  def member_descriptor
    "#{full_name} ( #{ Setting.first.display_rhq ? 'RHQ ' + region + " ," : ""} #{(teams.map { |t| t.name }.join' , ')} )  "
  end
  
  def send_sms(event, tenant)
    require 'messagebird'
    client = MessageBird::Client.new(ENV["MESSAGEBIRD_API"])
    response = client.message_create(tenant.truncate_words(1, omission: "")[0..10], "+65#{mobile_number}",
      "Hello #{first_name}, gentle reminder upcoming duty #{event.name} on #{event.start_date_time.strftime(Event.date_format)}. Please log-on to #{tenant} Portal to find out more."
    )
  end
  
  def self.create_member (user, params)
    @member = Member.new(params)
    @member.user = user
    @member.save(validate: false)
    @member
  end
  
  def self.search_members(search_params)
    
    name = search_params[:name].present? ? search_params[:name].downcase : nil
    team = search_params[:team].present? ? search_params[:team] : nil

    if !name.present? && !team.present?
      Member.all.paginate(page: search_params[:page], per_page: 10).order(:first_name)
    elsif name.present? && !team.present?
      Member.includes(:teams).paginate(page: search_params[:page], per_page: 10).where("(lower(first_name) LIKE ? 
        OR lower(last_name) LIKE ?
        OR (lower(first_name) || ' ' || lower(last_name)) LIKE ?)",
        "%#{name}%", "%#{name}%", "%#{name}%").references(:teams).order(:first_name) 
    else
      Member.includes(:teams).paginate(page: search_params[:page], per_page: 10).where("(lower(first_name) LIKE ? 
        OR lower(last_name) LIKE ?
        OR (lower(first_name) || ' ' || lower(last_name)) LIKE ?) 
        AND teams.id #{ !team.present? ? 'IS ' : '=' } ?",
        "%#{name}%", "%#{name}%", "%#{name}%", team).references(:teams).order(:first_name) 
    end
  
  end
  
  def self.search_members_report(search_params)
    from_start_date = search_params[:from_start_date].present? ? search_params[:from_start_date].to_time : 6.months.ago
    to_start_date =  search_params[:to_start_date].present? ? search_params[:to_start_date].to_time : 1.days.from_now
    team = search_params[:team].present? ? search_params[:team] : nil
    
    
    if team.present? 
      Member.includes(:teams, :events).where("
        (events.start_date_time BETWEEN ? AND ?) 
        AND teams.id #{ !team.present? ? 'IS NOT' : '=' } ?",
        "#{from_start_date}", "#{to_start_date}", team).references(:teams, :events).order("first_name")
    else
      Member.includes(:teams, :events).where("
        (events.start_date_time BETWEEN ? AND ?)",
        "#{from_start_date}", "#{to_start_date}",).references(:teams, :events).order("first_name") 
    end
  end
  
  def to_member_string
    "First Name: #{first_name} - 
    Last Name: #{last_name} - 
    mobile_number: #{mobile_number} - 
    Region: #{region} - 
    Street Name: #{street_name} - 
    Active Status: #{active_status} - 
    Role: #{role} - 
    PDPA: #{pdpa}"
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include VenuesHelper
  # uncomment to ensure common layout for forms
  # layout  "sign", :only => 
  
  before_action :authorized_admin_team_leader, except: [:change_tenant]

  def new()
    @member = Member.new()
    @user   = User.new()
  end

  def create()
    @user = User.new( user_params )
    params[:member][:active_status] = true

    # ok to create user, member
    if !User.where(email: @user.email).any? 
      if @user.save_and_invite_member() && Member.create_member( @user, member_params )
        flash[:notice] = "New member added and invitation email sent to #{@user.email}."
        redirect_to root_path
      else
        #flash[:error] = "errors occurred!"
        @member = Member.new( member_params ) # only used if need to revisit form
        MemberLogger.add_log(@member.id, "Member created by #{current_user.member.first.full_name}")
        render :new
      end
    else
      @exist_user = User.where(email: @user.email).first
      if @exist_user.tenants.where(id: Tenant.current_tenant.id).size == 0
        @exist_user.tenants << Tenant.current_tenant
        Member.create_member(@exist_user, member_params)
        @member = @exist_user.member
        MemberLogger.add_log(@member.ids.first, "Member created by #{current_user.member.first.full_name}")
        flash[:notice] = "#{@user.email} is added to #{Tenant.current_tenant.name}"
        MemberMailer.with(email: @user.email, member: @member).new_invite_memmber_email.deliver_now

      else
        flash[:danger] = "#{@user.email} is already added to #{Tenant.current_tenant.name}"
      end
      redirect_to root_path
    end

  end
  
  def edit
    @member = Member.find(params[:id])
    @member_logs = MemberLogger.where(member_id: @member.id).order(created_at: :desc)
  end
  
  def update
    @member = Member.find(params[:id])
    old_member = @member.to_member_string
    coordinates = get_coordinates(params[:member][:street_name])
    @member_logs = MemberLogger.where(member_id: @member.id).order(created_at: :desc)
    
    if coordinates.is_a?(String)
      @member.errors.add(:street_name, coordinates)
      render :edit
    else
      params[:member][:latitude] = coordinates[0]
      params[:member][:longitude] = coordinates[1]
      
      respond_to do |format|
        
        if @member.update(member_params)
          MemberLogger.add_log(@member.id, "Member updated by #{current_user.member.first.full_name} - [ Previous Details -> #{old_member} ] - [ New Details -> #{@member.to_member_string} ]")
          format.html { redirect_to members_path, notice: 'Member updated successfully.' }
        else
          
          format.html { render :edit }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  def index
    #@members = Member.all.paginate(page: params[:page], per_page: 10).order(:last_name)
  end
  
  def display_events_by_member
    @member_name = Member.find(params[:format]).full_name
    @member_events = Member.find(params[:format]).events.order(start_date_time: :desc).paginate(page: params[:page], per_page: 10)
  end
  
  def reactivate_member
    @member = Member.find(params[:format])
    @member.active_status = true
    @member.save
    flash[:notice] = "#{@member.full_name} is successfully reactivated."
    redirect_to members_path
  end
  
  def destroy
    @member = Member.find(params[:id])
    #@member.destroy
    @member.active_status = false
    @member.save
    
    flash[:notice] = "#{@member.full_name} is successfully suspended."
    redirect_to members_path
  end
  
  def change_tenant
    @tenant = Tenant.find_by_hashid(params["id"])
    session[:tenant_id] = @tenant.id
    Tenant.set_current_tenant(@tenant.id)
    redirect_to root_path
  end
  
  def search_members
    @members = Member.search_members(params)
    if @members
      respond_to do |format|
        format.js {render partial: 'members/display_members', obj: @members }
      end
    end
  end
  
  def display_members_report

  end

  def search_members_report
    @members = Member.search_members_report(params)
    @from_start_date = (params[:from_start_date].present? ? params[:from_start_date].to_time : 6.months.ago).strftime(Event.date_only_format)
    @end_start_date = (params[:to_start_date].present? ? params[:to_start_date].to_time : 1.days.from_now).strftime(Event.date_only_format)
    
    if @members
      respond_to do |format|
        format.js { render partial: 'members/display_members_report', obj: @members, from_start_date: @from_start_date, end_start_date: @end_start_date }
        format.xlsx         {
            response.headers[
              'Content-Disposition'
            ] = "attachment; filename=member-report.xlsx"
          }
      end
    end
  end

  private

  def member_params()
    params.require(:member).permit(:first_name, :last_name, :mobile_number, :region, :description, :street_name, :latitude, :longitude, :active_status, :role, team_ids:[] )
  end

  def user_params()
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_display_members.html.erb
<% if obj %>
  <% if obj.size > 0 %>
    <%= will_paginate obj,  list_classes: %w(pagination justify-content-center), previous_label: "Previous", next_label: "Next"  %>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th class="text-left">Name</th>
            <th class="text-center">Mobile No</th>
            <th class="text-center">Team</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% obj.each do |member| %> 
            <tr>
              <td><%= member.full_name %></td>
              <td class="text-center"><%= member.mobile_number %></td>
              <td class="text-center">
                <% member.teams.each do |team|  %>
                  <h6><span class="badge badge-pill badge-primary"><%= team.name %></span></h6>
                <% end %>
              </td>
              <td>
                <% if !member.active_status  %>
                  <%= link_to "<i class='fa fa-ban'></i> Member Suspended - View Past Events".html_safe, display_events_by_member_path(member), class: "#{cancel_button}" %>
                  <%= link_to "<i class='fa fa-refresh'></i> Reactivate".html_safe, reactivate_member_path(member), class: "btn btn-success btn-sm" %>
                <% elsif current_user.member.first != member %>
                  <%= link_to "<i class='fa fa-search-plus'></i> View Profile".html_safe, edit_member_path(member), class: "#{submit_button}"  %> 
                  <%= link_to "<i class='fa fa-calendar'></i> Events".html_safe, display_events_by_member_path(member), class: "#{submit_button}" %>
                  <%= link_to "<i class='fa fa-ban'></i> Suspend Member".html_safe, member_path(member), method: :delete, data: {confirm: "Are you sure?"}, class: "#{cancel_button}" %>
                <% else %>
                  To update, use "Edit My Profile" option.
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
        
      </table>
    </div>
    <%= will_paginate obj,  list_classes: %w(pagination justify-content-center), previous_label: "Previous", next_label: "Next"  %>
  <% else %>
    <div class="alert alert-danger" role="alert">
      No member found based on the current search parameters.
    </div>
  <% end %>
  <%= back_button %>
<% end %>

app/views/members/_display_members.js.erb
$('#results').html("<%= j ( render 'members/display_members.html', obj: @members) %>");
$('.pagination a').attr('data-remote', 'true');

app/views/members/_display_members_report.html.erb
<% if obj %>
  <% if obj.size > 0 %>
  <div class="row justify-content-between">
    <div class="col-auto">
      <h4>Attendance Report from <%= from_start_date %> to <%= end_start_date %></h4>
    </div>
    <div class="col-auto">
      <%= link_to "<i class='fa fa-file-excel-o'></i> Export to Excel Spreadsheet".html_safe, search_members_report_path(format: :xlsx), class: "#{transparent_button}" %>
    </div>
  </div>
      
    <div class="p-2"></div>
    <% #will_paginate obj,  list_classes: %w(pagination justify-content-center), previous_label: "Previous", next_label: "Next"  %>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th class="text-left">Name</th>
            <th class="text-center">Team</th>
            <th class="text-center">No. of Events</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% obj.each do |member| %> 
            <tr>
              <td class="text-left"><%= member.full_name %></td>
              <td class="text-center">
                <% member.teams.each do |team|  %>
                  <h6><span class="badge badge-pill badge-primary"><%= team.name %></span></h6>
                <% end %>
              </td>
              <td class="text-center"><%= member.events.size %></td>
              <td>
                <%= link_to "Events", display_events_by_member_path(member), class: "#{submit_button}" %>
              </td>
            </tr>
          <% end %>
        </tbody>
        
      </table>
    </div>
    <% #will_paginate obj,  list_classes: %w(pagination justify-content-center), previous_label: "Previous", next_label: "Next"  %>
  <% else %>
    <div class="alert alert-danger" role="alert">
      No member found based on the current search parameters.
    </div>
  <% end %>
<% end %>

app/views/members/_display_members_report.js.erb
$('#results').html("<%= j ( render 'members/display_members_report.html', obj: @members, from_start_date: @from_start_date, end_start_date: @end_start_date ) %>");
$('.pagination a').attr('data-remote', 'true');

app/views/members/display_events_by_member.html.erb
<h1  class="display-4"><%= @member_name%>'s Events</h1>
<%= render "/events/display_events", obj: @member_events %>

app/views/members/display_members_report.html.erb
<h1 class="display-4">Members' Attendance Report</h1>
<div class="p-2"></div>
<div id="event-lookup" class="card border-primary mb-3 rounded-0">
  <h6 class="card-header text-white bg-primary rounded-0">Search Parameters</h6>
  
  <%= form_tag search_members_report_path, remote: true, method: :get, id: "search-events-form" do %>
  <div class="card-body">
    <div class="form-row">
      <div class="form-group col">
        <div class="input-group date" id="datetimepicker7" data-target-input="nearest">
            <%= text_field_tag :from_start_date, nil,  class: "form-control datetimepicker-input", readonly: true, data: {target: "#datetimepicker7"}, placeholder: "From - Start Date" %>
            <div class="input-group-append" data-target="#datetimepicker7" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    
      <div class="form-group col">
        <div class="input-group date col" id="datetimepicker8" data-target-input="nearest">
          <%= text_field_tag :to_start_date, nil, class: "form-control datetimepicker-input", readonly: true, data: {target: "#datetimepicker8"}, placeholder: "To - Start Date" %>
            <div class="input-group-append" data-target="#datetimepicker8" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
      <div class="form-group col">
        <%= select_tag :team, options_from_collection_for_select(Team.all, :id, :team_descriptor),  {:class =>"selectpicker form-control", :title => "Team", :multiple => false, :data => {:'live-search' => true}} %>
      </div>
      </div>
    <div class="form-row">
      <div class="form-group col text-center">
        <%= button_tag type: "submit", class: "#{submit_button}" do %> <i class='fa fa-file-text-o'></i> Generate Report <% end %>
        <%= link_to "<i class='fa fa-ban'></i> Clear".html_safe, display_members_report_path, class: "#{cancel_button}" %> 
      </div>
    </div>
    </div>
  <% end %>
</div>

<div class="p-2"></div>

<div id="results">
  <%= render "display_members_report", obj: @members, from_start_date: @from_start_date, end_start_date: @end_start_date %>
</div>

<div class="pb-4"></div>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker7').datetimepicker({
            format: "DD-MMM-YYYY - h:mm A",
            stepping: 30,
            ignoreReadonly: true
        });
        $('#datetimepicker8').datetimepicker({
            useCurrent: false,
            format: "DD-MMM-YYYY - h:mm A",
            stepping: 30,
            ignoreReadonly: true
        });
        $("#datetimepicker7").on("change.datetimepicker", function (e) {
            $('#datetimepicker8').datetimepicker('minDate', e.date);
            $('#datetimepicker8').datetimepicker('date', e.date.add(2, 'hours'));
        });
        $("#datetimepicker8").on("change.datetimepicker", function (e) {
            //$('#datetimepicker7').datetimepicker('maxDate', e.date);
        });
        
        $(".selectpicker").selectpicker({
        }).selectpicker("render");
        
        $('.pagination a').attr('data-remote', 'true')
    });
</script>

app/views/members/edit.html.erb
<h1  class="display-4">Edit Member - <%= @member.full_name %></h1>

<div class="p-2"></div>
  <%= render "layouts/errors", object: @member %>


<%= form_for(@member) do |f| %>
  <div class="card border-primary mb-3 rounded-0">
    <h6 class="card-header bg-primary text-white rounded-0">Member Basic Information</h6>
      <div class="card-body text-dark">
        
        <div class="form-row">
          <div class="form-group col">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
          <div class="form-group col">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
          <%= f.label :mobile_number %>
          <%= f.text_field :mobile_number, class: "form-control" %>
          </div>
          
          <div class="form-group col">
            <%= f.label "Home Street Name" %>
            <%= f.text_field :street_name, class: "form-control" %>
            <small class="form-text text-muted">Enter your home street name in full, such as Tampines Street 81. Please <font color="red"><strong>DO NOT</strong></font> enter block or unit number.</small>
          </div>
      </div>
    </div>
  </div>
  <div class="card border-primary mb-3 rounded-0">
    <h6 class="card-header bg-primary text-white rounded-0">Member Advanced Information</h6>
      <div class="card-body text-dark">
        <div class="form-row">
          <div class="form-group col">
            <%= f.label :role  %>
            <%= f.select :role, options_for_select(current_user.member.first.try(:admin?) ? Member.roles.map {|k, v| [k.humanize.capitalize, k]} : Member.roles.first(2).map {|k, v| [k.humanize.capitalize, k]}, selected: @member.role || nil), {}, class: "form-control" %>
          </div>
          
          <div class="form-group col">
            <%= f.label :region, "Region (RHQ)" %> <small>If you do not have a RHQ, enter "NA".</small>
            <%= f.text_field :region, class: "form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
            <%= f.label "Team" %>
            <%= f.collection_select :team_ids, Team.all.order(:name), :id, :team_descriptor, {},  {:class =>"selectpicker form-control show-tick", :multiple => true, :data => {:'live-search' => true }} %>
          </div>
          
        </div>
        <div class="form-row">
          <div class="form-group col">
            <%= f.label "More Information About the Member" %>
            <%= f.text_area :description, class: "form-control" %>
          </div> 
        </div>
      </div>
  </div>
  <div class="p-2"></div>

  <div class="form-group">
    <%= button_tag type: "submit", class: "#{submit_button}", data: { disable_with: "Updating..."} do %> <i class='fa fa-user'></i> Update Member <% end %>
    <% if current_user.member.first.try(:admin?) %>
    <button class="<%= submit_button %>" type="button" data-toggle="collapse" data-target="#memberhistory" aria-expanded="false" aria-controls="collapseExample">
      <i class='fa fa-history'></i> Show Member History
    </button>
    <div class="p-2"></div>
    <div class="collapse" id="memberhistory">
      <div class="card border-dark mb-3 rounded-0">
        <div class="card-header"><strong>Member Update History</strong></div>
          <ul class="list-group list-group-flush">
            <% @member_logs.each do |member_log| %>
              <li class="list-group-item" style="font-size: 0.7em"><%= member_log.member_log %></li>
            <% end %>
          </ul>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
    $(function () {

        $(".selectpicker").selectpicker({
        }).selectpicker("render");
    });
</script>

app/views/members/index.html.erb
<h1  class="display-4">Search Members</h1>
<div class="p-2"></div>

<div id="member-lookup" class="card border-primary mb-3 rounded-0">
  <h6 class="card-header text-white bg-primary rounded-0">Search Parameters</h6>
  
  <%= form_tag search_members_path, remote: true, method: :get, id: "search-members-form" do %>
  <div class="card-body">
    <div class="form-row">
      <div class="form-group col">
        <%= text_field_tag :name, params[:name], placeholder: "Name", autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group col">
        <%= select_tag :team, options_from_collection_for_select(Team.all, :id, :team_descriptor),  {:class =>"selectpicker form-control", :title => "Team", :multiple => false, :data => {:'live-search' => true}} %>
      </div>

    </div>
    <div class="form-row">
      <div class="form-group col text-center">
        <%= button_tag type: "submit", class: "#{submit_button}" do %> <i class='fa fa-users'></i> Search Members <% end %>
        <%= link_to "<i class='fa fa-refresh'></i> Clear".html_safe, members_path, class: "#{submit_button}" %> 
        <%= back_button %>

      </div>
    </div>
    </div>
  <% end %>
</div>

<div class="p-2"></div>
<div id="results">
  <%= render "display_members", obj: @members %>
</div>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker7').datetimepicker({
            format: "DD-MMM-YYYY - h:mm A",
            stepping: 30,
            ignoreReadonly: true
        });
        $('#datetimepicker8').datetimepicker({
            useCurrent: false,
            format: "DD-MMM-YYYY - h:mm A",
            stepping: 30,
            ignoreReadonly: true
        });
        $("#datetimepicker7").on("change.datetimepicker", function (e) {
            $('#datetimepicker8').datetimepicker('minDate', e.date);
            $('#datetimepicker8').datetimepicker('date', e.date.add(2, 'hours'));
        });
        $("#datetimepicker8").on("change.datetimepicker", function (e) {
            //$('#datetimepicker7').datetimepicker('maxDate', e.date);
        });
        
        $(".selectpicker").selectpicker({
        }).selectpicker("render");
        
        $('.pagination a').attr('data-remote', 'true')
    });
</script>

app/views/members/new.html.erb
<h1 class="display-4">Invite New Member</h1>
<%= render "layouts/errors", object: @user %>
<%= render "layouts/errors", object: @member %>

<div class="card border-primary mb-3 rounded-0">
  <h6 class="card-header bg-primary text-white rounded-0">New Member</h6>
  <div class="card-body">
    <%= form_with(model: Member, local: true) do |form| %>
      <div class="form-row">
      <%= fields_for( :user ) do |w| %>
        
          <div class="control-group col">
          <%= w.label :email %>
            <div class="controls">
              <%= w.text_field :email, class: "form-control", required: true  %>
            </div>
          </div>
        
      <% end %>
        <div class="control-group col">
          <%= form.label :role %>
          <div class="controls">
            <%= form.select(:role, options_for_select( current_user.member.first.try(:admin?) ? Member.roles.map {|k, v| [k.humanize.capitalize, k]} : Member.roles.first(2).map {|k, v| [k.humanize.capitalize, k]} ), {}, {class: "form-control"}) %>
          </div>
        </div>
      </div>
  
    <div class="form-row">
      <div class="col">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "form-control", required: true  %>
      </div>
  
      <div class="col">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: "form-control", required: true  %>
      </div>
    </div>
    
    <div class="p-2"></div>
    
    <div class="actions">
      <%= button_tag type: "submit", class: "#{submit_button}" do %> <i class='fa fa-user'></i> Create User and Invite <% end %> <%= back_button %>
    </div>
  <% end %>
  </div>
</div>